export enum RoleKey {
  IMMEDIATE_PAST_PRESIDENT = 'IMMEDIATE_PAST_PRESIDENT',
  PRESIDENT = 'PRESIDENT',
  VP_EDUCATION = 'VP_EDUCATION',
  ASSOCIATE_VPE = 'ASSOCIATE_VPE',
  VP_MEMBERSHIP = 'VP_MEMBERSHIP',
  ASSOCIATE_VPM = 'ASSOCIATE_VPM',
  VP_PUBLIC_RELATIONS = 'VP_PUBLIC_RELATIONS',
  ASSOCIATE_VPPR = 'ASSOCIATE_VPPR',
  SECRETARY = 'SECRETARY',
  TREASURER = 'TREASURER',
  SERGEANT_AT_ARMS = 'SERGEANT_AT_ARMS',
  MEMBER = 'MEMBER',
}
