export enum AGENDA_ROLE {
  PRESIDENT = 'PRESIDENT',
  SAA = 'SAA',
  TOASTMASTER = 'TOASTMASTER',
  TIMER = 'TIMER',
  GRAMMARIAN = 'GRAMMARIAN',
  AH_COUNTER = 'AH_COUNTER',
  GENERAL_EVALUATOR = 'GENERAL_EVALUATOR',
  TABLE_TOPIC_MASTER = 'TABLE_TOPIC_MASTER',
  SPEAKER = 'SPEAKER',
  EVALUATOR = 'EVALUATOR',
}
