import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import slugify from 'slugify';

import { Event } from "../modules/events/entities/event.entity";
import { CreateEventDto } from "../modules/events/dto/createEvent.dto"
import { UpdateEventDto } from "../modules/events/dto/updateEvent.dto"

@Injectable()
export class EventsService {
  private readonly logger = new Logger(EventsService.name);

  constructor(
    @InjectRepository(Event)
    private readonly eventRepo: Repository<Event>,
  ) {}

  // ================= HELPER =================
  private toArray(value?: string | string[]): string[] {
    if (!value) return [];
    if (Array.isArray(value)) return value;
    return value
      .split(',')
      .map((v) => v.trim())
      .filter(Boolean);
  }

  // ================= CREATE =================
  async create(dto: CreateEventDto): Promise<Event> {
    const event = this.eventRepo.create({
      ...dto,
      date: dto.date || undefined, // handle optional date
      agenda: this.toArray(dto.agenda),
      tags: this.toArray(dto.tags),
      // slug will be generated by @BeforeInsert in entity
    });

    const savedEvent = await this.eventRepo.save(event);
    this.logger.log(`Event created | id=${savedEvent.id}`);
    return savedEvent;
  }

  // ================= FIND ALL =================
  async findAll(): Promise<Event[]> {
    return this.eventRepo.find();
  }

  // ================= FIND BY SLUG =================
  async findOneBySlug(slug: string): Promise<Event> {
    const event = await this.eventRepo.findOne({ where: { slug } });
    if (!event) {
      throw new NotFoundException(`Event with slug "${slug}" not found`);
    }
    return event;
  }

  // ================= UPDATE BY SLUG =================
  async updateBySlug(slug: string, dto: UpdateEventDto): Promise<Event> {
    const event = await this.findOneBySlug(slug);

    this.logger.debug(
      `Updating event | slug=${slug} | payload=${JSON.stringify(dto)}`,
    );

    if (dto.title !== undefined) {
      event.title = dto.title;
      // regenerate slug on title change
      const baseSlug = slugify(dto.title, { lower: true, strict: true });
      const uniqueSuffix = Math.random().toString(36).substring(2, 8);
      event.slug = `${baseSlug}-${uniqueSuffix}`;
    }

    if (dto.description !== undefined) event.description = dto.description;
    if (dto.overview !== undefined) event.overview = dto.overview;
    if (dto.date !== undefined) event.date = dto.date || undefined;
    if (dto.location !== undefined) event.location = dto.location;
    if (dto.venue !== undefined) event.venue = dto.venue;
    if (dto.time !== undefined) event.time = dto.time;
    if (dto.mode !== undefined) event.mode = dto.mode;
    if (dto.audience !== undefined) event.audience = dto.audience;
    if (dto.image !== undefined) event.image = dto.image;
    if (dto.agenda !== undefined) event.agenda = this.toArray(dto.agenda);
    if (dto.organizer !== undefined) event.organizer = dto.organizer;
    if (dto.tags !== undefined) event.tags = this.toArray(dto.tags);

    const updatedEvent = await this.eventRepo.save(event);
    this.logger.log(
      `Event updated | id=${updatedEvent.id} | slug=${updatedEvent.slug}`,
    );

    return updatedEvent;
  }

  // ================= REMOVE BY SLUG =================
  async removeBySlug(slug: string): Promise<Event> {
    const event = await this.findOneBySlug(slug);
    await this.eventRepo.remove(event);
    this.logger.log(`Event removed | id=${event.id} | slug=${event.slug}`);
    return event;
  }
}